---
title: "Covid-19 na América Latina"
output: 
    flexdashboard::flex_dashboard:
    orientation: rows
  
---

```{r setup, include=FALSE}
library(flexdashboard)
setwd('C:/Users/danie/OneDrive/Documentos/ProEpi/Covid_19_AL/dados_OMS')
dados_OMS = read.csv('20200524_OMS_globaldata.csv', stringsAsFactors = F)
dados_AML = subset(dados_OMS, dados_OMS$Country == "Argentina"|
                     dados_OMS$Country == "Bolivia (Plurinational State of)"|
                     dados_OMS$Country == "Brazil"|
                     dados_OMS$Country == "Chile"|
                     dados_OMS$Country == "Colombia"|
                     dados_OMS$Country == "Costa Rica"|
                     dados_OMS$Country == "Cuba"|
                     dados_OMS$Country == "El Salvador"|
                     dados_OMS$Country == "Ecuador"|
                     dados_OMS$Country == "Guatemala"|
                     dados_OMS$Country == "Haiti"|
                     dados_OMS$Country == "Honduras" |
                     dados_OMS$Country == "Mexico"|
                     dados_OMS$Country == "Nicaragua"|
                     dados_OMS$Country == "Panama" |
                     dados_OMS$Country == "Paraguay" |
                     dados_OMS$Country == "Peru" |
                     dados_OMS$Country == "Dominican Republic" |
                     dados_OMS$Country == "Uruguay" |
                     dados_OMS$Country == "Venezuela (Bolivarian Republic of)")

pop = data.frame( cbind(c("Argentina", "Bolivia (Plurinational State of)", "Brazil", 
                          "Chile", "Colombia", "Costa Rica", "Cuba", "El Salvador",
                    "Ecuador", "Guatemala", "Haiti", "Honduras", "Mexico", "Nicaragua",
                    "Panama", "Paraguay", "Peru", "Dominican Republic", "Uruguay",
                 "Venezuela (Bolivarian Republic of)"),
                 c(43590368 , 10969049, 210147125, 
                    18050000, 48747632, 4868148, 11221060,
                    6344722, 16385068, 17263239, 9996731, 9587522, 123675325, 6167237,
                    4034119, 7152703, 33105273, 10630000, 3351016, 31703499)))
colnames(pop) = c("Country", "Pop")

dados_AML = merge(dados_AML, pop, by = "Country")
dados_AML$day = substring(dados_AML$`ï..Date_reported`, 1, 10)
dados_AML$day = as.Date(dados_AML$day)
dados_AML$New_cases = ifelse(dados_AML$New_cases < 0, 0, dados_AML$New_cases)
```

Column 
-------------------------------------
    
### Número de casos na América Latina (Até 24 de maio de 2020)
    
```{r}
library(flexdashboard)
casos = sum(dados_AML$New_cases)
valueBox(casos, icon = "fa-user-friends", color = '#3236a8')
```
 
### Óbitos na América Latina (Até 24 de maio de 2020)
    
```{r}
obitos = sum(dados_AML$New_deaths)
valueBox(obitos, icon = "fa-clock", color = '#a83e32')
``` 
 
### Letalidade na América Latina (Até 24 de maio de 2020)
    
```{r}
letalidade = paste0(round(obitos/casos*100, 2), "%")
valueBox(letalidade,icon = "fa-exclamation", color = '#db1620')
``` 

Row {data-height=350}
-------------------------------------
    
### Incidência na América Latina
    
```{r}
library(ggplot2)
library(scales)

#histograma de casos 
casos = ggplot(dados_AML, aes(day, New_cases))
casos+ 
  geom_bar(stat="identity", fill = '#70a0be')+
  scale_x_date(breaks="5 days", labels=date_format("%d/%m"))+
  ggtitle('Número de casos confirmados de Covid-19 por dia, América Latina, 24 de maio de 2020')+
  ylab("Casos") + xlab("Dia") +
  theme_bw() 
```
    
### Óbitos na América Latina

```{r}
#histograma de Óbitos
obitos = ggplot(dados_AML, aes(day, New_deaths))
obitos+ 
  geom_bar(stat="identity", fill = '#f6968d')+
  scale_x_date(breaks="5 days", labels=date_format("%d/%m"))+
  ggtitle('Número de óbitos por Covid-19 por dia, América Latina, 24 de maio de 2020')+
  ylab("óbitos") + xlab("Dia") +
  theme_bw()
```


